docker-compose-yaml: docker-compose.yml

project: drupal-example-simple

ssh: ssh.main.lagoon-core.test6.amazee.io:22
api: https://api.main.lagoon-core.test6.amazee.io/graphql

environment_variables:
  git_sha: 'true'

tasks:
  pre-rollout:
    - 
      run:
        name: Always write cluster id to pre-rollout file
        command: echo $LAGOON_KUBERNETES > /tmp/test-0-pre-rollout
        service: cli
        shell: bash
        when: exists("LAGOON_KUBERNETES")
    - 
      run:
        name: Show results
        command: ls -al /tmp/test-*
        service: cli
        shell: bash
  post-rollout:
    -
      run:
        name: drush updb
        command: drush -y updb
        service: cli
    - 
      run:
        name: drush cr
        command: drush -y cr
        service: cli

backup-retention:
  production:
    hourly: 48
    daily: 185

environments:
  test6:
    # routes:
    cronjobs:
      - name: drush cron
        schedule: "*/30 * * * *"
        command: drush cron --debug
        service: cli
