docker-compose-yaml: docker-compose.yml

project: drupal-example-simple

ssh: ssh.main.lagoon-core.test6.amazee.io:22
api: https://api.main.lagoon-core.test6.amazee.io/graphql

environment_variables:
  git_sha: 'true'

tasks:
  pre-rollout:
    - run:
        name: Working env
        command: env
        service: cli
        RequiresEnvironment: false

  post-rollout:
    # Enable once config sync has been setup.
    # - run:
    #     name: drush cim
    #     command: drush -y cim
    #     service: cli
    - run:
        name: print env
        command: env
        service: cli
    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli
    

backup-retention:
  production:
    hourly: 168
    daily: 185

environments:
  9.x:
    # routes:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
