docker-compose-yaml: docker-compose.yml

project: test6-drupal-example-simple

ssh: token.main.lagoon-core.test6.amazee.io:22
api: https://api.main.lagoon-core.test6.amazee.io/graphql

environment_variables:
  git_sha: 'true'

tasks:
  pre-rollout:
    - 
      run:
        name: Always write cluster id to pre-rollout file
        command: echo $LAGOON_KUBERNETES > /tmp/test-0-pre-rollout
        service: cli
        shell: bash
        when: exists("LAGOON_KUBERNETES")
    - 
      run:
        name: Show results
        command: ls -al /tmp/test-*
        service: cli
        shell: bash
  post-rollout:
    - 
      run:
        name: Check if development
        command: touch /tmp/test-1-development
        service: cli
        shell: bash
        when: LAGOON_ENVIRONMENT_TYPE=="development"
    - 
      run:
        name: Check if not production
        command: touch /tmp/test-2-not-production
        service: cli
        shell: bash
        when: LAGOON_ENVIRONMENT_TYPE!="production"
    - 
      run:
        name: Check if development
        command: touch /tmp/test-3-production-should-not-write
        service: cli
        shell: bash
        when: LAGOON_ENVIRONMENT_TYPE=="production"
    - 
      run:
        name: Check git branch regex
        command: touch /tmp/test-4-branch-regex
        service: cli
        shell: bash
        when: LAGOON_GIT_BRANCH=~".*-broken"
    - 
      run:
        name: Check variable exists
        command: touch /tmp/test-5-var-exists
        service: cli
        shell: bash
        when: exists("LAGOON_KUBERNETES")
    - 
      run:
        name: Check added build variable exists
        command: touch /tmp/test-6-env-var-exists
        service: cli
        shell: bash
        when: TASK_TEST_VAR=="task"
    - 
      run:
        name: Run with non-added variable with default
        command: touch /tmp/test-7-default-var
        service: cli
        shell: bash
        when: withDefault("TASK_ADDITIONAL_TEST_VAR", "true") == "true"
    - 
      run:
        name: Show results
        command: ls -al /tmp/test-*
        service: cli
        shell: bash
    - 
      run:
        name: Show env in php
        command: env
        service: nginx
        container: php
    -
      run:
        name: drush updb
        command: drush -y updb
        service: cli
    - 
      run:
        name: drush cr
        command: drush -y cr
        service: cli
    - 
      run:
        name: errors and output
        command: echo "test1 stdout" && sleep 1 && echo "test2 stderr" 1>&2 && sleep 1 && echo "test3 stderr" 1>&2 && sleep 1 && echo "test4 stdout"
        service: cli
        shell: bash

backup-retention:
  production:
    hourly: 48
    daily: 185

routes:
  autogenerate:
    enabled: false

environments:
  test6:
    routes:
      - nginx:
        - testroute.test6.amazee.io:
            tls-acme: 'true'
            insecure: Allow
        - testroute.example.com:
            tls-acme: 'true'
            insecure: Allow
    cronjobs:
      - name: drush crondemonium
        schedule: "*/30 * * * *"
        command: drush cron --debug
        service: cli

lagoon-sync:
  ssh:
    host: ssh.main.lagoon-core.test6.amazee.io
    port: 22
  mariadb:
    config:
      hostname: "${MARIADB_HOST:-mariadb}"
      username: "${MARIADB_USERNAME:-drupal}"
      password: "${MARIADB_PASSWORD:-drupal}"
      port: "${MARIADB_PORT:-3306}"
      database: "${MARIADB_DATABASE:-drupal}"
  files:
    config:
      sync-directory: "/app/web/sites/default/files"
  drupalconfig:
    config:
      syncpath: "./config/sync"
